{{- if .Values.mcmtp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "mcmtp.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "mcmtp.labels" . | nindent 4 }}
  {{- if .Values.mcmtp.ingress.annotations }}
  annotations: {{ .Values.mcmtp.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{ $root := . }}
    {{- range .Values.mcmtp.ingress.hostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: /_matrix/corporal/policy
            pathType: Prefix
            backend:
              service:
                name: {{ template "mcmtp.basename" $root }}
                port:
                  number: 80
    {{- end }}
  tls:
    {{- range .Values.mcmtp.ingress.hostnames }}
    - hosts:
        - {{ . | quote }}
      secretName: {{ printf "%s-tls" . }}
    {{- end }}
{{- end }}
