{{- if not .Values.mcmtp.secrets.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mcmtp.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "mcmtp.labels" . | nindent 4 }}
stringData:
  config.json: |{{ .Values.mcmtp.config | toJson | nindent 4}}
{{- end }}